CREATE DATABASE NBA;
USE NBA;
CREATE TABLE `teamgamelog` (
  `idTeamGameLog` int(11) NOT NULL,
  `Season` varchar(10) DEFAULT NULL,
  `SeasonType` varchar(45) DEFAULT NULL,
  `TeamId` varchar(10) DEFAULT NULL,
  `GameId` varchar(10) DEFAULT NULL,
  `Game_Date` varchar(15) DEFAULT NULL,
  `MatchUp` varchar(20) DEFAULT NULL,
  `WL` varchar(1) DEFAULT NULL,
  `SeasonWins` int(11) DEFAULT NULL,
  `SeasonLosses` int(11) DEFAULT NULL,
  `SeasonWinPerc` decimal(5,3) DEFAULT NULL,
  `Minutes` int(11) DEFAULT NULL,
  `FGM` int(11) DEFAULT NULL,
  `FGA` int(11) DEFAULT NULL,
  `FG_Perc` decimal(5,3) DEFAULT NULL,
  `FG3M` int(11) DEFAULT NULL,
  `FG3A` int(11) DEFAULT NULL,
  `FG3_Perc` decimal(5,3) DEFAULT NULL,
  `FTM` int(11) DEFAULT NULL,
  `FTA` int(11) DEFAULT NULL,
  `FT_Perc` decimal(5,3) DEFAULT NULL,
  `OREB` int(11) DEFAULT NULL,
  `DREB` int(11) DEFAULT NULL,
  `REB` int(11) DEFAULT NULL,
  `AST` int(11) DEFAULT NULL,
  `STL` int(11) DEFAULT NULL,
  `BLK` int(11) DEFAULT NULL,
  `TOV` int(11) DEFAULT NULL,
  `PF` int(11) DEFAULT NULL,
  `PTS` int(11) DEFAULT NULL,
  PRIMARY KEY (`idTeamGameLog`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
